site_name: Yao Class C++ Studio
repo_url: https://github.com/yao-class-cpp-studio/wiki
edit_uri: edit/main/docs/
plugins:
  - search:
      lang:
        - en
        - ja
# dev_addr: 0.0.0.0:8000
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Using dark mode
      primary: deep purple
      accent: deep purple
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Using light mode
  icon:
    repo: fontawesome/brands/github
    logo: material/language-cpp
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - footnotes
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - assets/css/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/xterm/3.14.5/xterm.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js
  - https://cdnjs.cloudflare.com/ajax/libs/xterm/3.14.5/xterm.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/xterm/3.14.5/addons/fit/fit.min.js
  - assets/js/wasm-clang/shared.js
  - assets/js/cpp_runner.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: README.md
  - Lectures:
    - "01 Intro to C": lectures/01.md
    - "02 C Basics": lectures/02.md
  - Toolchain:
    - 编译器: toolchain/compiler.md
    - git: toolchain/git.md
    - CMake: toolchain/cmake.md
    - libpng: toolchain/libpng.md
  - Assignments:
    - Assignment 4: assignments/assignment-4.md
    - Project 1: assignments/project-1.md
