site_name: C++ Studio
repo_url: https://github.com/yao-class-cpp-studio/wiki
edit_uri: edit/main/docs/
plugins:
  - search:
      lang:
        - en
        - ja
# dev_addr: 0.0.0.0:8000
theme:
  name: material
  palette:
    - scheme: default
      primary: white
  icon:
    repo: fontawesome/brands/github
    logo: material/language-cpp
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
    - content.action.edit
markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - footnotes
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
extra_css:
  - assets/css/styles.css
  - assets/css/asciinema-player.css
  - https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/xterm/3.14.5/xterm.min.css
  - https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/KaTeX/0.15.2/katex.min.css
extra_javascript:
  # https://cdn.bytedance.com/
  - https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/ace/1.4.14/ace.min.js
  - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/xterm/3.14.5/xterm.js
  - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/xterm/3.14.5/addons/fit/fit.min.js
  - assets/js/wasm-clang/shared.js
  - assets/js/cpp_runner.js
  - assets/js/asciinema-player.min.js  # 3.0.1
  - assets/js/index.js
  - https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/KaTeX/0.15.2/katex.min.js
nav:
  - Home: README.md
  # - Lectures:
  #   - "01 Intro to C": lectures/01.md
  #   - "02 C Basics": lectures/02.md
  #   - "07 STL & Modern C++": lectures/07.md
  - Toolchain:
    - toolchain/README.md
    - 配置开发环境: toolchain/environment/README.md
    - 命令行:
      - toolchain/shell/README.md
      - SSH: toolchain/shell/ssh.md
      - 包管理: toolchain/shell/package.md
    - 网络基础:
      - toolchain/network/README.md
      - 常见软件代理设置: toolchain/network/common.md
      - WSL中会出现的问题: toolchain/network/wsl.md
    - Git新手入门:
      - toolchain/git/README.md
      - 进阶-配置Git: toolchain/git/config.md
      - 进阶-Git的分支管理: toolchain/git/branch.md
      - 进阶-Git的命令行操作: toolchain/git/command.md
      - 高阶-Git原理: toolchain/git/principle.md
      - 高阶-多远程管理: toolchain/git/remote.md
      - 高阶-修改历史: toolchain/git/history.md
      - 参考-Git命令速查表: toolchain/git/cheatsheet.md
    - Conda: toolchain/conda/README.md
    - CMake: toolchain/cmake.md
    - Vulkan SDK: toolchain/vulkan/README.md
    - libpng: toolchain/libpng.md
    - vcpkg: toolchain/vcpkg.md
    - Grassland: toolchain/grassland/README.md
  # - Assignments:
  #   - Assignment 4: assignments/assignment-4.md
    # - Project 1: assignments/project-1.md
  - OJ: https://oj.cpp.studio/
