on:
  push:
    branches:
      - main
      - 'releases/**'

name: Build and Deploy

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Build Documents
      run: |
        mkdocs build
    - name: Upload files
      run: |
        pip install awscli
        export AWS_ACCESS_KEY_ID=${{ secrets.COS_SECRET_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.COS_SECRET_KEY }}
        aws s3 sync ./site/ s3://${{ secrets.COS_BUCKET }}/ \
          --endpoint-url https://cos.${{ secrets.COS_REGION }}.myqcloud.com \
          --delete \
          ;
