on:
  push:
    branches:
      - main
      - 'releases/**'

name: Build and Deploy

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Build Documents
      run: |
        mkdocs build
    - name: Upload files (coscmd)
      env:
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        COS_BUCKET: ${{ secrets.COS_BUCKET }}   # e.g. my-bucket-1250000000
        COS_REGION: ${{ secrets.COS_REGION }}   # e.g. ap-singapore
      run: |
        pip install --upgrade coscmd
        coscmd config -a "$COS_SECRET_ID" -s "$COS_SECRET_KEY" -b "$COS_BUCKET" -r "$COS_REGION"
        # Optional tuning:
        # coscmd config -m 20 -p 10   # 20 threads, 10 MB part size

        # One-time cleanup (old objects uploaded with aws-chunked may be broken):
        # If this bucket/prefix is dedicated to the site, uncomment once:
        # coscmd delete -rf /

        # Upload contents of ./site/ to bucket root
        coscmd upload -rs ./site/ /
